### ISSUE TITLE
Amazon Cloud Drive support

### ISSUE THREAD

**Issue by kelna** [henrysher/duplicity#3]
Hi,
it would be very nice to have native support for ACD, since it gives unlimited storage very cheap, which makes it the ideal backup solution. There isn't a solution so far on Linux for backup to ACD.

Amazon has an API for third parties. It is different from S3, but available. Several windows programs use it.

Cheers,
kelna

**Comment by kelna** [comment]
Maybe it's worth to take a look at the **acd_cli** and **acd_fuse** projects.

**Comment by kelna** [comment]
acd_cli is the way to go, if anyone wonders:
https://github.com/yadayada/acd_cli

**Comment by mals** [comment]
I've written a backend for duplicity which uses acd_cli which you can find here:

https://entangledthought.wordpress.com/2015/11/06/duplicity-and-amazon-cloud-drive/

I'm still testing it out but feel free to give it a spin.

**Comment by kelna** [comment]
Thanks for the heads up. Although I use duplicati now, because duplicity couldn't finish the initial backup. If I didn't finish it in one run (and it was impossible), duplicity deleted *everything* from the target and started over. Duplicati doesn't have such problem, although it has other downsides like being very slow after a couple thousand files have been written to the target, but it works.

Anyways, thanks for the update, it's a nice piece of software!

**Comment by kelna** [comment]
Oh, zoiks! I misclicked...

**Comment by breunigs** [comment]
@mals your solution was quite a nice starter, but unfortunately has some problems. For instance, it doesn’t upload the signature files and thus breaks incremental backups and probably also restores. I’ve put your code into a github repository and applied all necessary fixes: https://github.com/breunigs/duplicity-acdcli

**Comment by mals** [comment]
Thanks Stefan! I initially wrote this for an older version of duplicity
using MultiDrive.py and quickly ported it to acd_cli without fully testing
it. But thanks for testing it out and sorting out the bugs. Hopefully we
can feed this into the duplicity code base at some point.

**Comment by lachesis** [comment]
Now bundled with duplicity.

**Comment by languitar** [comment]
If it is bundled, why is this issue still open? Are there any docs on how to use this?

**Comment by breunigs** [comment]
Only support through third party tool "acd_cli" is included as of now. The ticket asks for native support.  I have an implementation for that, but no keys from Amazon who take their sweet time. 

You can use the acdcli backend by specifying acd+acdcli://path/on/acd. Google on how to setup acdcli, it's a bit of a pain since it is not packaged by most distributions last time I checked.

**Comment by Thinkscape** [comment]
acd_cli is easy to set up. Take a look here:
https://github.com/yadayada/acd_cli/blob/master/docs/setup.rst
https://github.com/yadayada/acd_cli/blob/master/docs/authorization.rst
https://github.com/yadayada/acd_cli/blob/master/docs/usage.rst

Full docs here: https://acd-cli.readthedocs.io/en/latest/

**Comment by ThomasSteinbach** [comment]
A couple of weeks are gone and I have to repeat the question of @languitar why this issue is still open? Because - and this is awesome - thanks to @breunigs the current implementation of his Amazon Drive backend works like a charm without any acd_cli stuff ( https://github.com/breunigs/duplicity-amazondrive ). Even in the source code of his backend there is statet that the implementation _"does not rely on externally setup software (like acd_cli)"_ I tested his backend with duplicity 0.7.06 and meanwhile use it in production.

Here is my Docker Container to reproduce: https://hub.docker.com/r/thomass/duplicity

This issue should be solved as with duplicity 0.8+

**Comment by flurischt** [comment]
FYI: https://www.reddit.com/r/DataHoarder/comments/6awuvk/i_had_access_to_others_file_in_acd/ 
The GitHub issue has been deleted but you can check web.archive.org. You may want to check the implementable before integrating this or depending on some services from there.
